package team017.message;

public enum MessageType {
	BORDER, BUILDING_REQUEST, CONSTRUCTION_COMPLETE,
	BUILDING_LOCATION_INQUIRY_MESSAGE, BUILDING_LOCATION_RESPONSE_MESSAGE,
	FOLLOW_ME_MESSAGE, SCOUTING_MESSAGE, ENEMY_INFORMATION_MESSAGE, GRID_MAP_MESSAGE
}
