package team017.message;

public enum MessageType {
	BORDER, BUILDING_REQUEST, CONSTRUCTION_COMPLETE, ENEMY_LOCATION,
	BUILDING_LOCATION_INQUIRY_MESSAGE, BUILDING_LOCATION_RESPONSE_MESSAGE,
	FOLLOW_ME_MESSAGE
}
